### ISSUE TITLE
Broken in latest betas

### ISSUE THREAD

**Issue by J3LS** [Darcvizer/Destructive-Extrude#5]
An error message is given and the command fails in both the Linux and Windows versions in the latest Blender betas. I tried creating the new face with the knife and snap utilities tool - same result. It was working about 4-6 versions ago. I had old copies of the Windows version but not the Linux.

Here's the output:
Read prefs: /home/jeff/.config/blender/2.80/config/userpref.blend
found bundled python: /home/jeff/Blender28/2.80/python
Warning: property 'deselect' not found in keymap item 'GPENCIL_OT_select_circle'
Read blend: /home/jeff/Desktop/extrude.blend
fake_module: addon missing 'bl_info' gives bad performance!: '/home/jeff/.config/blender/2.80/scripts/addons/Destructive-Extrude2.py'
Warning: property 'deselect' not found in keymap item 'GPENCIL_OT_select_circle'
Writing userprefs: '/home/jeff/.config/blender/2.80/config/userpref.blend' ok
Traceback (most recent call last):
  File "/home/jeff/.config/blender/2.80/scripts/addons/Destructive-Extrude.py", line 412, in invoke
    CursorPosition(self,context)
  File "/home/jeff/.config/blender/2.80/scripts/addons/Destructive-Extrude.py", line 124, in CursorPosition
    self.CursorLocation = context.scene.cursor_location
AttributeError: 'Scene' object has no attribute 'cursor_location'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by J3LS** [comment]
I found the conversation on Blender Artists - sorry, new to this. I've now downloaded ver 1.0.0 and it works fine. Thanks for your great work.
